{# base.phtml #}

{# 注意：如果发现模板不起作用，请删除 cache/volt/ 下面的缓存文件 #}

<!DOCTYPE html>
<html lang="{{ lang }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= isset($title) ? $title . ' - ' : '' ?><?= gettext('web.title') ?></title>

    <?php if ('production' == APPLICATION_ENV) { ?>
        {# CDN 资源 #}
        <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
        <!-- Bootstrap core CSS -->
        <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://use.fontawesome.com/ab418d22ce.js"></script>
    <?php } else { ?>
        {# 本地资源 #}
    <?php } ?>


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://v3.bootcss.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {# 插入其它的资源到页面的头部 #}
    {% block headerAssets %}{% endblock %}
</head>
<body>

<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">系统 Demo</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav"></ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user %}

                <li class="<?= \lyu\uphalcon\library\helper\UMenu::active('/index/server') ?>"><a
                            href="{{ url('/index/server') }}">菜单一</a></li>

                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        {{ user['account'] }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="http://u.dev/user" target="_blank">个人信息</a></li>
                        <li><a href="{{ url('index/index/logout') }}">退出</a></li>
                    </ul>
                </li>

                {% else %}
                <li class="<?= \lyu\uphalcon\library\helper\UMenu::active('/demo/index') ?>"><a
                            href="{{ url('/demo/index') }}">当前菜单</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container" style="margin-top: 50px;">
    <p><?php $this->flashSession->output() ?></p>
    {% block content %}{% endblock %}

</div> <!-- /container -->

</body>
<?php if ('production' == APPLICATION_ENV) { ?>
    {# CDN 资源 #}
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v3.bootcss.com/assets/js/ie10-viewport-bug-workaround.js"></script>
<?php } else { ?>
    {# 本地资源 #}
<?php } ?>
{# 插入其它 js 到页面的底部 #}
{% block footerAssets %}{% endblock %}
</html>
